### ISSUE TITLE
This is old.

### ISSUE THREAD

**Issue by n01e0** [Percivalll/fanotify-rs#2]
The code here is from version 0.2.7, but the version available on crates.io is 0.2.10.

**Comment by ZhangLei-cn** [comment]
Yes,I'll update the code.
The next version is v0.3.0 which will contain two crates:fanotify-sys(low-level) and fanotify-rs(high-level).It will support common kernel versions(especially the versions where the fanotify API has changed).

**Comment by Congee** [comment]
Ummm, now it's the contrary :sweat_smile: . creates.io shows 0.2.10 published on August 19th, 2020, but github shows 0.3.0 https://github.com/ZhangLei-cn/fanotify-rs/blob/4987bc7f784330cc86cdba79e7a04f2f8aa27885/Cargo.toml#L3

**Comment by pantsman0** [comment]
0.3.1 has been released to crates.io
