### ISSUE TITLE
low_level::fanotify_read hardcodes 200 events and does not handle libc::EAGAIN

### ISSUE THREAD

**Issue by Congee** [Percivalll/fanotify-rs#4]
Hi, this create looks neat. I like it :smiley: There is a piece of code that I don't quite understand. Can you explain a bit?

https://github.com/ZhangLei-cn/fanotify-rs/blob/4987bc7f784330cc86cdba79e7a04f2f8aa27885/src/low_level.rs#L374-L389

There are two problems:
1. What happens if there are more than 200 events to read? This wouldn't be a big problem if events of a queue are handled soon enough.
2. An error returned by `libc::read` is not handled. `libc::malloc` can return ENOMEM when there is no enough memory, right?

**Comment by pantsman0** [comment]
Hi Congee,

1. If there are more than 200 events, 200 will be returned and the function will need to be called again to drain more from the queue. Unfortunately the line just needs to be drawn somewhere and Percivalll just decided at 200.

2. The error case for `libc::read` is handled by the check of `sizeof > 0` as the error codes are negative - the API does not bubble up the errors though. As for `malloc`, this is true but unlikely for a 4800 byte allocation - it has been replaced with a heap allocated buffer (`Box<[u8;4800]>`) in a testing branch for version 0.3.1.

**Comment by pantsman0** [comment]
Fixed by release of 0.3.1
