### ISSUE TITLE
Could we keep the code in `crate.io` up to date?

### ISSUE THREAD

**Issue by sctb512** [Percivalll/fanotify-rs#9]
The code in crate.io is old.

**Comment by pantsman0** [comment]
Hi @sctb512.

I have just been added to the project, and I'm working on getting it updated. In the meantime, if you are still interested in the crate, would you be so kind as to test the `refactor` branch?

**Comment by sctb512** [comment]
@pantsman0 Thank you for the invitation. I am so sorry, I have no time for this at the moment.

**Comment by sctb512** [comment]
Are you posting this branch to `crate.io`? I think I can help check if the new version works.

**Comment by pantsman0** [comment]
If it helps, I can push a release candidate tomorrow.

**Comment by pantsman0** [comment]
@sctb512 I have uploaded version `0.3.1-rc1` onto crates.io . I will be testing it with my project, but I would still appreciate any feedback you have.

**Comment by pantsman0** [comment]
0.3.1 has been pushed to crates.io
